
export const defaultQuotes = [`I'm going to the picnic, and I'm bringing asbestos insulation, brined shrimp, the cryogenically frozen head of Walt Disney, a dromedary, and... a eurocentric view of world history. Where's your rock & roll power now? Hippie! You know, I really should broaden my social horizons. And I thought you were on your way to a sci-fi convention. I don't like to smile unless I have a reason.`,

`Can you concisely and unemotionally sum up for us the doctrine of Manifest Destiny? Ten dollar surcharge if I have to spend more than fifteen minutes with the parents. Gee, Mom and Dad never told us that people can think for themselves. I should really make pancakes more often. The batter's so sensual. Thrown out of college without enrolling first? I'm damn proud of you.`,

`So I said, "Just because people are cliquey and snotty is no reason not to like them." Well, you're not your usually sunny self. Looks like a sandwich... and it's an antique! You know, self-esteem is a little like your car's brake fluid. You may not even know you're low on it until, one day, you go to shift gears and nothing happens. ...That's transmission fluid! Nice conversational skills.`,

`If they start to drive you nuts, tell them you know this great game called "cemetery." They have to lie on the floor and pretend they're dead. The first one to move or make a sound loses. Ah, Brittany. Sometimes, despite a complete lack of insight, you stumble upon an interesting answer. You honor, let me make it clear at the outset that this is not a witch hunt. You've got the kind of looks that make other girls mentally ill. If I'm not back in ten minutes, don't send help.`,

`It's good to see you both enterprising! I could make a trite observation about wishing you were as enterprising toward your school work as you are to this effort to find financing for a new place to loaf, but am I the sort of man who engages in trite observations, Brittany? It's our policy to be tough, especially on youthful transgressors. Fourteen people pretended not to see me, five crossed the street to get away, seven ran, three called the police, and I'm pretty sure this one guy fired a shot. Now, girls, you're little kittens in an animal shelter. You have to look sad and helpless so someone will adopt you, or else it's kitty heaven. A lot of good men died in that conflict, Kevin. I believe we owe it to them to at least get the century right!`,
]