const seasonOne = [
`I'm just saying you don't make friends as easily as... uh, some people.`,
`I'll try to help her through this difficult period of adjustment.`,
`Don't worry. It's a psychological test. You're automatically exempt.`,
`Um... a herd of beautiful wild ponies running free across the plains.`,
`Last time I took one of these tests, they told me they were clouds. They said they could be whatever I wanted.`,
`Daria, can you concisely and unemotionally sum up for us the doctrine of Mainfest Destiny?`,
`A lot of good men died in that conflict, Kevin. I believe we owe it to them to at least get the century right!`,
`Well, my history teacher hates me because I know all the answers, but there are some interesting idiots in my class.`,
`Not much chance of that happening... unless there's uranium in the drinking water here, too`,
`We tell you over and over again that you're wonderful and you just... don't... get it! What's wrong with you?!`,
`Is she going to have, like, a breakdown or something? 'Cause that could really mess me up with my new friends.`,
`Don't worry. I don't have low self-esteem. It's a mistake. I have low esteem for everyone else.`,
`But we are here to begin realizing your actuality... and when we do, each and every one of you will be able to stand proudly and proclaim, "I am."`,
`He doesn't know what it means. He's got the speech memorized. Just enjoy the nice man's soothing voice.`,
`Nocturnal emissions.`,
`I could pass the test, but I like having low self-esteem. It makes me feel special.`,
`I'm taking the rest of the day off to work with you on your self-esteem.`,
`U.F.O. conventions, once sneered at as the domain of so-called "kooks," have become big, big business, drawing hundreds of thousands of people each year, people as sane and rational as you and I, who come simply to satisfy a normal curiosity.`,
`And once again, the bake sale was a tremendous success. We raised more than $400, which was subsequently stolen from the office, but I am confident we will get that money back. In a related note, the school nurse will be visiting homerooms tomorrow to collect DNA samples.`,
`Usually when I have this dream I'm wearing pink taffeta.`,
`You know, self-esteem is a little like your car's brake fluid. You may not even know you're low on it until, one day, you go to shift gears and nothing happens. ...That's transmission fluid!`,
`Knowing that I have self-esteem gives me even more self-esteem. On the other hand, having all of you know that I had low self-esteem makes me feel... kind of bad... like a big failure or something.`,
`I don't know. My self-esteem feels like it's starting to slip.`,
`Let's go get our picture taken with the cardboard alien.`,
`I'll wait here... or in the ladies' room.. or maybe out in the parking lot.`,
`Careful. Don't hurt yourself with that scrunchie.`,
`Perspective is hard.`,
`I'm thinking of going into politics.`,
`You can't expect me to choose a boyfriend right away. That would be like eating the first pancake off the stove. You have to feed one to the dog.`,
`Well, you could show me how to twirl hair around my little finger and look vacant.`,
`I know what you mean... and that scares me.`,
`Hey, even though I'm much more popular, we have some things in common.`,
`I mean, you're not popular, but you're not so unpopular that you couldn't come to my party Saturday night.`,
`Gee, Brittany. I'm overcome with emotion.`,
`Oh, yeah. That particular model was quite bursty. I think she had her bursts done.`,
`Sure. And after that, I think I'll swallow glass.`,
`It won't work. My face is too expressive.`,
`Sheer, semi-sheer, or opaque? ...Textured! `,
`Go away, I'm concentrating. I'm invited to a party Saturday night and I have to choose the perfect outfit.`,
`You know, I really should broaden my social horizons.`,
`Hey, stuff like that doesn't matter. The most popular people with the best-looking hair -- that's what makes a great party.`,
`Daria, would you say sleeping with a guitar in your hands counts as practicing? ...As long as you don't drop it.`,
`I have a problem dealing with authority.`,
`A high school party? Please. Don't you think I'm a little mature for that?`,
`Nice conversational skills.`,
`So I said, "Just because people are cliquey and snotty is no reason not to like them."`,
`Now she's really popular, but not as popular as she is. He's medium popular, and he just bought a great car so soon he'll be getting more popular. That guy was just popular enough to be invited, but now he needs to hook up with a girl who's more popular than he is.`,
`This is Jane. She wasn't invited, but she's good in art.`,
`I dissected her frog.`,
`Now, she used to be very popular, but then then there was that unfortunate nose job. That one behind the tiger? She was new and cute so she became, like, popular overnight. Those three aren't popular at all. I don't know what they're doing here. Maybe some kind of exchange program.`,
`The one in the green shirt is cute... in a head-too-big-for-his-body kind of way.`,
`Hey. Partying hard or hardly partying? ...Hardly interested.`,
`We were born in this room, we grew up in this room, and we thought we would die here... alone. But now you've arrived, and our lives can truly begin.`,
`Aren't you a little out of place here? And everywhere else on Earth?`,
`Well, I have been saving up for a pair of snappy orthopedic shoes.`,
`What do you plan to do about it? You can't ignore me! I pay your salary. Are you sleeping in there? You're not a real cop, you know!`,
` It's the Soul Train. Beep-beep. Get on board.`,
`You seem awfully young to be doing this kind of work.`,
`It's a disguise, ma'am. We're actually much older. Not as old as you, of course, ma'am.`,
`The wall-to-wall carpeting in the bathrooms makes up for it.`,
`To your left, the home of the town director of public works, built on unstable landfill. To your right, a flattened squirrel. Straight ahead, the future!`,
`I've been working on the railroad... come on, guys, we know this one.`,
`It was dead already, sweetheart. Just like the others.`,
`I think people who run over animals should get run over themselves to see how they like it.`,
`Can we get on with this? I have someplace to go. Television counts as a place.`,
`She's got a dark, threatened look. She never cracked no books. La-la-la...`,
`Superb! Now I can use your dorm room to carry on affairs with some of the more beautiful undergraduates. Thank you!`,
`How come even in my fantasies everyone's a jerk?`,
`Money well spent, since it wasn't my money.`,
`It's not a date. We're meeting to discuss scholarship options.`,
`There's no such thing as a making-out scholarship.`,
`These buildings date from when Middleton was a colonial religious college. Back then, the all-male student body attended chapel twice a day, and endured whippings as punishment for impure thoughts.`,
`Then you'd better get over there and help clean the house steps, or the Council of Ancients will give you a noodle whipping you won't soon forget.`,
`She's God's problem now, kid. Let's get out of here. This place gives me the creeps.`,
`Actually, I'm sending an erotic letter to a female inmate I met on the Internet. I think she's female.`,
`There's also the part about working a stupid job and begging your parents for money.`,
`My psych term paper. Finally. Nobody respects deadlines anymore. It was a collaboration. My part was to say how long it should be and when it was due.`,
`But cash only. I don't take checks from college students.`,
`Um, I'm just a freshman and I... we're not really supposed to... I get headaches sometimes 'cause I'm allergic to things. And I... I sort of have to go now, bye.`,
`It's a candy store. That's their business. They sell candy. And make loans. Oh, and haul trash. They got a variety of interests, actually.`,
`Second, unless your ex-boyfriend is an authority on D.H. Lawrence, don't base your thesis on something he said while making out.`,
`You seem pretty comfortable with the brain-dead. So, let's go to a party.`,
`Excuse me, ma'am. Could I trouble you for your underwear?`,
`But you look so cute when you say funny words. Besides, shouldn't you be saving your quarters for taking us out?x`,
`Ah, they've chosen the Keg Queen. It's a huge honor. She gets to drive the kegs to and from the distributor.`,
`They made me their queen! Isn't it great?!`,
`Uh, are we going to need to know this, or is this, like, personal advice or something?`,
`Thrown out of college without enrolling first. I'm damn proud of you.`,
`I have two econ problem sets and a paper on Kerouac that I have to get to the delivery guy by 9:00 P.M.... and then, I quit.`,
`I already feel burned out on college and I'm still in high school.`,
`She said it was wrong to encourage cheaters and to profit from them. ...So, she's giving up being a lawyer?`,
`Does that mean these are the best years of our lives? I hope not.`,
`I can't take anymore of this Shakespeare dude, bro. He's, like, a total chick writer!`,
`Like, why should I be interested in anything this Shakespeare guy says?`,
`Come together with the planet? By staring at a screen for hours? Sitting in a room full of people you never say a word to?`,
`Then I'd like to register as a conscientious objector.`,
`Hi! No dinner for me! Emergency meeting of the Fashion Club!`,
`I'll make up a nice plate for you and cover it up with cling wrap.`,
`I'll throw another steak on the grill.`,
`Can't talk now. I'm chairing a meeting of the Resting Quietly Club.`,
`Um, no... but I once had to recite the Gettysburg Address wearing a rainbow wig and panties that said "Tuesday." Whatever made me want to join a fraternity?`,
`Maybe that one about feeling like a big misfit whom everybody hates. The other kids will really relate to that. I know I do.`,
`No way, baby.`,
`Come on. Do it for friendship.`,
`I have no friends. I walk alone.`,
`Then do it for the opportunity to look inside people's houses and find out what screwed-up tastes they have.`,
`I'm bringing a Polaroid.`,
`You've come, no doubt, to apologize for your academic performance.`,
`It's good to see you both enterprising! I could make a trite observation about wishing you were as enterprising toward your school work as you are to this effort to find financing for a new place to loaf, but am I the sort of man who engages in trite observations, Brittany?`,
`Now, while you're on a roll, am I the sort of man who you suppose believes in underwriting the indolence of students who already display the work habits of garden slugs?`,
`Hi! I'm selling long distance phone cards.`,
`Well, I enjoy chocolate. Doctor says I'm not supposed to have too much of it, but he wouldn't mind if it's for a good cause.`,
`Just, just, I was in the basement when the doorbell rang. Need to catch my breath a little. How many chocolate bars you got there?`,
`You sure that's okay with your doctor?`,
`We could call your doctor or the hospital if you like. Otherwise, we'll be going.`,
`I don't need a damn doctor, I need a damn chocolate bar! Gimme! I'll pay ya five bucks apiece!`,
`Yeah, and all we had to do was take a human life.`,
`You always see the downside, don't you?`,
`Did she ask you to feed her the chocolate?`,
`She has no family. She ate them.`,
`So, your refusal to sell chocolate to this woman was based purely on concern for her welfare....And not wanting to do time for manslaughter.`,
`I'm here. But where are you? Sure, I see your body. Anybody home in that rotting bag of flesh? `,
`See? You don't want to do poetry for this crowd.`,
`You think it's too late for me to learn juggling?`,
`Can anyone give me a concrete representation of this abstract theory?`,
`The mall is a dangerous influence on today's teens and the fluorescent lights give you seizures.`,
`I'm sorry, Mrs. Bennett. I can't go to the mall. I have a skin condition.`,
`I'm not your teammate. I'm your girlfriend! We talked about the difference, remember?`,
`Do you think it would dishonor Dr. King's memory if I went to sit in the back of the bus?`,
`Ladies! Are you aware of the advantages of a gold card? Very advantageous when it belongs to your father. Dad wants me to pick up some bikinis for his secretary.`,
`Upchuck, are you aware that many therapists now accept credit cards?`,
`Who would ever guess there'd be so many colors? The person who thought them all up must be a genius.`,
`I always look for security guards leading away someone in handcuffs. Shoplifters are the best judges of merchandise.`,
`The Doo Dad Shop. Oh, good. I've always wanted my own doo dad.`,
`An encyclopedia is an unusual product for a supermodel to promote, isn't it?`,
`My mother's threatening to redecorate again.`,
`Isn't modeling about dropping out of school to pursue a career based solely on your youth and your looks, both of which are inevitably declared over by age twenty-five?`,
`And don't fashion people squander their lives loudly worshiping all that is superficial and meaningless while the planet keeps riding a roller coaster to hell?`,
`We're finally going to get those bulletproof skylights for the swimming pool.`,
`You really ought to stick to mineral water and parsley.`,
`You know, you don't always have to be against everything.`,
`The fashion industry may be considered a perfect implementer of marketplace psychology. The business insures its own survival by training consumers to focus on arbitrary styling distinctions, rather than quality and durability.`,
`Oh, look at you. So waif-like... so pouty. Could you remove your glasses?`,
`I can't take my glasses off. I need them to see scam artists.`,
`All right, ladies, your worst enemy is at the end of the catwalk. The one who stole your boyfriend. She has fallen and broken her leg. Your job is to tell her, without words, that you've come to watch them cut it off.`,
`Ah, Quinn, that is excellent. You appear truly to be savoring another's misfortune.`,
`Now, girls, you're little kittens in an animal shelter. You have to look sad and helpless so someone will adopt you, or else it's kitty heaven.`,
`I knew I should've stayed home.`,
`And then I thought, if I sign up with a charity now, before I'm famous, later on I can say, "Oh! I was helping others long before I started modeling."`,
`Sad to say, America no longer engages in the kind of ground wars that made this country great! But that doesn't mean that savage hand-to-hand combat is out of your reach.`,
`You call that a pose? You're not flexing for your milkmaid girlfriend anymore!`,
`And like a husband going home to his noble and self-sacrificing wife, the rat keeps returning to the food box. That is, the positive reinforcement. Huh, if only men could be more like rats. Oh, sure, they come home at first. You feed them, you wait on them, and then, after twenty-two thankless years, they just up and leave. No note, no phone call, no nothing!`,
`Can anyone give me another example of a group using coercive techniques such as peer pressure, chanting, and social isolation to achieve control over its members?`,
`Ah, Brittany. Sometimes, despite a complete lack of insight, you stumble upon an interesting answer.`,
`She'll never have to worry about mind control. ...No, but she'll have to watch out for ferrets building a nest in her head.`,
`She's well liked among classmates of both sexes, and yet, strangely, she turns my stomach.`,
`Some are weird. Some are just astonishingly self-centered and deceitful.`,
`They bake cookies by day, but they really heat up the night! G-string grandmas, today on Sick, Sad World.`,
`This color looks nothing like melon. It's way too pink.`,
`You know, I used to wear mini-skirts... but life goes on.`,
`But I didn't mean to double-book. It's hard to keep track of dates when you're attractive and popular.`,
`Ten dollar surcharge if I have to spend more than fifteen minutes with the parents.`,
`If they start to drive you nuts, tell them you know this great game called "cemetery." They have to lie on the floor and pretend they're dead. The first one to move or make a sound loses.`,
`And the vocabulary word for tonight is "indemnification."`,
`I know that plenty of guys want to go out with you, and plenty of girls want to go out with me, and that makes me think we should be together.`,
`Raisins are nature's candy.`,
`So Cinderella skipped the ball and asked her fairy Godmother to make her the first woman president. Realizing that the monarchy was becoming obsolete, the prince opened a video store.`,
`And then, the little engine decided that he just wasn't the competitive type.`,
`So Old Mother Hubbard tracked down the deadbeat loser and made him pay child support.`,
`And the dish ran away with the spoon, but Hawaii was the only state which would recognize the marriage as legal.`,
`And the truth is, no one will ever ask to see your permanent record.`,
`Gee, Mom and Dad never told us that people can think for themselves.`,
`We made up that part about aliens living under the North Pole.`,
`Tonight, on Sick, Sad World, a prime-time special about people just like you, only more pathetic.`,
`Daria, your paper was excellent, and the original research was thought-provoking, although it would probably be considered a felony in most states.`,
`I mean, when a woman is elected president, it won't be because she got breast implants.`,
`Fourteen people pretended not to see me, five crossed the street to get away, seven ran, three called the police, and I'm pretty sure this one guy fired a shot.`,
`From the first time man and woman gazed upon themselves in the ripples of a sun-dappled pool, human beings have been blessed, and burdened, by awareness of their own image. But what does this have to do with your thighs?`,
`Of course it's gonna be harder to breathe, hon. Those nostrils are itty-bitty compared to the ones you had. Try breathing through your mouth.`,
`Oh, honey, nothing wrong with that nose. It's a pretty little schnoz!`,
`We all know about the terrible atrocities caused by America's lust for veal, but here's something nice you can do for calves: calf implants!`,
`I hate to see a young lady give up on herself at such a early age.`,
`Maybe you can inject collagen into your lips in the shape of a smile.`,
`Humor may lift your spirits, Daria, but it takes a professional to lift your buttocks! Doctor's joke! Have a nice day girls. And remember, money can make anyone look beautiful.`,
`If I didn't have such low self-esteem, she might have gotten to me.`,
`Aren't you a little worried that there may be a hell?`,
`You know, maybe I should get boobs. I bet if I got some boobs on credit, I can get the rest of the money in no time.`,
`You've got the kind of looks that make other girls mentally ill.`,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
]