const seasonOne = [
`I'm just saying you don't make friends as easily as... uh, some people.`,
`I'll try to help her through this difficult period of adjustment.`,
`Don't worry. It's a psychological test. You're automatically exempt.`,
`Um... a herd of beautiful wild ponies running free across the plains.`,
`Last time I took one of these tests, they told me they were clouds. They said they could be whatever I wanted.`,
`Daria, can you concisely and unemotionally sum up for us the doctrine of Mainfest Destiny?`,
`A lot of good men died in that conflict, Kevin. I believe we owe it to them to at least get the century right!`,
`Well, my history teacher hates me because I know all the answers, but there are some interesting idiots in my class.`,
`Not much chance of that happening... unless there's uranium in the drinking water here, too`,
`We tell you over and over again that you're wonderful and you just... don't... get it! What's wrong with you?!`,
`Is she going to have, like, a breakdown or something? 'Cause that could really mess me up with my new friends.`,
`Don't worry. I don't have low self-esteem. It's a mistake. I have low esteem for everyone else.`,
`But we are here to begin realizing your actuality... and when we do, each and every one of you will be able to stand proudly and proclaim, "I am."`,
`He doesn't know what it means. He's got the speech memorized. Just enjoy the nice man's soothing voice.`,
`Nocturnal emissions.`,
`I could pass the test, but I like having low self-esteem. It makes me feel special.`,
`I'm taking the rest of the day off to work with you on your self-esteem.`,
`U.F.O. conventions, once sneered at as the domain of so-called "kooks," have become big, big business, drawing hundreds of thousands of people each year, people as sane and rational as you and I, who come simply to satisfy a normal curiosity.`,
`And once again, the bake sale was a tremendous success. We raised more than $400, which was subsequently stolen from the office, but I am confident we will get that money back. In a related note, the school nurse will be visiting homerooms tomorrow to collect DNA samples.`,
`Usually when I have this dream I'm wearing pink taffeta.`,
`You know, self-esteem is a little like your car's brake fluid. You may not even know you're low on it until, one day, you go to shift gears and nothing happens. ...That's transmission fluid!`,
`Knowing that I have self-esteem gives me even more self-esteem. On the other hand, having all of you know that I had low self-esteem makes me feel... kind of bad... like a big failure or something.`,
`I don't know. My self-esteem feels like it's starting to slip.`,
`Let's go get our picture taken with the cardboard alien.`,
`I'll wait here... or in the ladies' room.. or maybe out in the parking lot.`,
`Careful. Don't hurt yourself with that scrunchie.`,
`Perspective is hard.`,
`I'm thinking of going into politics.`,
`You can't expect me to choose a boyfriend right away. That would be like eating the first pancake off the stove. You have to feed one to the dog.`,
`Well, you could show me how to twirl hair around my little finger and look vacant.`,
`I know what you mean... and that scares me.`,
`Hey, even though I'm much more popular, we have some things in common.`,
`I mean, you're not popular, but you're not so unpopular that you couldn't come to my party Saturday night.`,
`Gee, Brittany. I'm overcome with emotion.`,
`Oh, yeah. That particular model was quite bursty. I think she had her bursts done.`,
`Sure. And after that, I think I'll swallow glass.`,
`It won't work. My face is too expressive.`,
`Sheer, semi-sheer, or opaque? ...Textured! `,
`Go away, I'm concentrating. I'm invited to a party Saturday night and I have to choose the perfect outfit.`,
`You know, I really should broaden my social horizons.`,
`Hey, stuff like that doesn't matter. The most popular people with the best-looking hair -- that's what makes a great party.`,
`Daria, would you say sleeping with a guitar in your hands counts as practicing? ...As long as you don't drop it.`,
`I have a problem dealing with authority.`,
`A high school party? Please. Don't you think I'm a little mature for that?`,
`Nice conversational skills.`,
`So I said, "Just because people are cliquey and snotty is no reason not to like them."`,
`Now she's really popular, but not as popular as she is. He's medium popular, and he just bought a great car so soon he'll be getting more popular. That guy was just popular enough to be invited, but now he needs to hook up with a girl who's more popular than he is.`,
`This is Jane. She wasn't invited, but she's good in art.`,
`I dissected her frog.`,
`Now, she used to be very popular, but then then there was that unfortunate nose job. That one behind the tiger? She was new and cute so she became, like, popular overnight. Those three aren't popular at all. I don't know what they're doing here. Maybe some kind of exchange program.`,
`The one in the green shirt is cute... in a head-too-big-for-his-body kind of way.`,
`Hey. Partying hard or hardly partying? ...Hardly interested.`,
`We were born in this room, we grew up in this room, and we thought we would die here... alone. But now you've arrived, and our lives can truly begin.`,
`Aren't you a little out of place here? And everywhere else on Earth?`,
`Well, I have been saving up for a pair of snappy orthopedic shoes.`,
`What do you plan to do about it? You can't ignore me! I pay your salary. Are you sleeping in there? You're not a real cop, you know!`,
` It's the Soul Train. Beep-beep. Get on board.`,
`You seem awfully young to be doing this kind of work.`,
`It's a disguise, ma'am. We're actually much older. Not as old as you, of course, ma'am.`,
`The wall-to-wall carpeting in the bathrooms makes up for it.`,
`To your left, the home of the town director of public works, built on unstable landfill. To your right, a flattened squirrel. Straight ahead, the future!`,
`I've been working on the railroad... come on, guys, we know this one.`,
`It was dead already, sweetheart. Just like the others.`,
`I think people who run over animals should get run over themselves to see how they like it.`,
`Can we get on with this? I have someplace to go. Television counts as a place.`,
`She's got a dark, threatened look. She never cracked no books. La-la-la...`,
`Superb! Now I can use your dorm room to carry on affairs with some of the more beautiful undergraduates. Thank you!`,
`How come even in my fantasies everyone's a jerk?`,
`Money well spent, since it wasn't my money.`,
`It's not a date. We're meeting to discuss scholarship options.`,
`There's no such thing as a making-out scholarship.`,
`These buildings date from when Middleton was a colonial religious college. Back then, the all-male student body attended chapel twice a day, and endured whippings as punishment for impure thoughts.`,
`Then you'd better get over there and help clean the house steps, or the Council of Ancients will give you a noodle whipping you won't soon forget.`,
`She's God's problem now, kid. Let's get out of here. This place gives me the creeps.`,
`Actually, I'm sending an erotic letter to a female inmate I met on the Internet. I think she's female.`,
`There's also the part about working a stupid job and begging your parents for money.`,
`My psych term paper. Finally. Nobody respects deadlines anymore. It was a collaboration. My part was to say how long it should be and when it was due.`,
`But cash only. I don't take checks from college students.`,
`Um, I'm just a freshman and I... we're not really supposed to... I get headaches sometimes 'cause I'm allergic to things. And I... I sort of have to go now, bye.`,
`It's a candy store. That's their business. They sell candy. And make loans. Oh, and haul trash. They got a variety of interests, actually.`,
`Second, unless your ex-boyfriend is an authority on D.H. Lawrence, don't base your thesis on something he said while making out.`,
`You seem pretty comfortable with the brain-dead. So, let's go to a party.`,
`Excuse me, ma'am. Could I trouble you for your underwear?`,
`But you look so cute when you say funny words. Besides, shouldn't you be saving your quarters for taking us out?x`,
`Ah, they've chosen the Keg Queen. It's a huge honor. She gets to drive the kegs to and from the distributor.`,
`They made me their queen! Isn't it great?!`,
`Uh, are we going to need to know this, or is this, like, personal advice or something?`,
`Thrown out of college without enrolling first. I'm damn proud of you.`,
`I have two econ problem sets and a paper on Kerouac that I have to get to the delivery guy by 9:00 P.M.... and then, I quit.`,
`I already feel burned out on college and I'm still in high school.`,
`She said it was wrong to encourage cheaters and to profit from them. ...So, she's giving up being a lawyer?`,
`Does that mean these are the best years of our lives? I hope not.`,
`I can't take anymore of this Shakespeare dude, bro. He's, like, a total chick writer!`,
`Like, why should I be interested in anything this Shakespeare guy says?`,
`Come together with the planet? By staring at a screen for hours? Sitting in a room full of people you never say a word to?`,
`Then I'd like to register as a conscientious objector.`,
`Hi! No dinner for me! Emergency meeting of the Fashion Club!`,
`I'll make up a nice plate for you and cover it up with cling wrap.`,
`I'll throw another steak on the grill.`,
`Can't talk now. I'm chairing a meeting of the Resting Quietly Club.`,
`Um, no... but I once had to recite the Gettysburg Address wearing a rainbow wig and panties that said "Tuesday." Whatever made me want to join a fraternity?`,
`Maybe that one about feeling like a big misfit whom everybody hates. The other kids will really relate to that. I know I do.`,
`No way, baby.`,
`Come on. Do it for friendship.`,
`I have no friends. I walk alone.`,
`Then do it for the opportunity to look inside people's houses and find out what screwed-up tastes they have.`,
`I'm bringing a Polaroid.`,
`You've come, no doubt, to apologize for your academic performance.`,
`It's good to see you both enterprising! I could make a trite observation about wishing you were as enterprising toward your school work as you are to this effort to find financing for a new place to loaf, but am I the sort of man who engages in trite observations, Brittany?`,
`Now, while you're on a roll, am I the sort of man who you suppose believes in underwriting the indolence of students who already display the work habits of garden slugs?`,
`Hi! I'm selling long distance phone cards.`,
`Well, I enjoy chocolate. Doctor says I'm not supposed to have too much of it, but he wouldn't mind if it's for a good cause.`,
`Just, just, I was in the basement when the doorbell rang. Need to catch my breath a little. How many chocolate bars you got there?`,
`You sure that's okay with your doctor?`,
`We could call your doctor or the hospital if you like. Otherwise, we'll be going.`,
`I don't need a damn doctor, I need a damn chocolate bar! Gimme! I'll pay ya five bucks apiece!`,
`Yeah, and all we had to do was take a human life.`,
`You always see the downside, don't you?`,
`Did she ask you to feed her the chocolate?`,
`She has no family. She ate them.`,
`So, your refusal to sell chocolate to this woman was based purely on concern for her welfare....And not wanting to do time for manslaughter.`,
`I'm here. But where are you? Sure, I see your body. Anybody home in that rotting bag of flesh? `,
`See? You don't want to do poetry for this crowd.`,
`You think it's too late for me to learn juggling?`,
`Can anyone give me a concrete representation of this abstract theory?`,
`The mall is a dangerous influence on today's teens and the fluorescent lights give you seizures.`,
`I'm sorry, Mrs. Bennett. I can't go to the mall. I have a skin condition.`,
`I'm not your teammate. I'm your girlfriend! We talked about the difference, remember?`,
`Do you think it would dishonor Dr. King's memory if I went to sit in the back of the bus?`,
`Ladies! Are you aware of the advantages of a gold card? Very advantageous when it belongs to your father. Dad wants me to pick up some bikinis for his secretary.`,
`Upchuck, are you aware that many therapists now accept credit cards?`,
`Who would ever guess there'd be so many colors? The person who thought them all up must be a genius.`,
`I always look for security guards leading away someone in handcuffs. Shoplifters are the best judges of merchandise.`,
`The Doo Dad Shop. Oh, good. I've always wanted my own doo dad.`,
`An encyclopedia is an unusual product for a supermodel to promote, isn't it?`,
`My mother's threatening to redecorate again.`,
`Isn't modeling about dropping out of school to pursue a career based solely on your youth and your looks, both of which are inevitably declared over by age twenty-five?`,
`And don't fashion people squander their lives loudly worshiping all that is superficial and meaningless while the planet keeps riding a roller coaster to hell?`,
`We're finally going to get those bulletproof skylights for the swimming pool.`,
`You really ought to stick to mineral water and parsley.`,
`You know, you don't always have to be against everything.`,
`The fashion industry may be considered a perfect implementer of marketplace psychology. The business insures its own survival by training consumers to focus on arbitrary styling distinctions, rather than quality and durability.`,
`Oh, look at you. So waif-like... so pouty. Could you remove your glasses?`,
`I can't take my glasses off. I need them to see scam artists.`,
`All right, ladies, your worst enemy is at the end of the catwalk. The one who stole your boyfriend. She has fallen and broken her leg. Your job is to tell her, without words, that you've come to watch them cut it off.`,
`Ah, Quinn, that is excellent. You appear truly to be savoring another's misfortune.`,
`Now, girls, you're little kittens in an animal shelter. You have to look sad and helpless so someone will adopt you, or else it's kitty heaven.`,
`I knew I should've stayed home.`,
`And then I thought, if I sign up with a charity now, before I'm famous, later on I can say, "Oh! I was helping others long before I started modeling."`,
`Sad to say, America no longer engages in the kind of ground wars that made this country great! But that doesn't mean that savage hand-to-hand combat is out of your reach.`,
`You call that a pose? You're not flexing for your milkmaid girlfriend anymore!`,
`And like a husband going home to his noble and self-sacrificing wife, the rat keeps returning to the food box. That is, the positive reinforcement. Huh, if only men could be more like rats. Oh, sure, they come home at first. You feed them, you wait on them, and then, after twenty-two thankless years, they just up and leave. No note, no phone call, no nothing!`,
`Can anyone give me another example of a group using coercive techniques such as peer pressure, chanting, and social isolation to achieve control over its members?`,
`Ah, Brittany. Sometimes, despite a complete lack of insight, you stumble upon an interesting answer.`,
`She'll never have to worry about mind control. ...No, but she'll have to watch out for ferrets building a nest in her head.`,
`She's well liked among classmates of both sexes, and yet, strangely, she turns my stomach.`,
`Some are weird. Some are just astonishingly self-centered and deceitful.`,
`They bake cookies by day, but they really heat up the night! G-string grandmas, today on Sick, Sad World.`,
`This color looks nothing like melon. It's way too pink.`,
`You know, I used to wear mini-skirts... but life goes on.`,
`But I didn't mean to double-book. It's hard to keep track of dates when you're attractive and popular.`,
`Ten dollar surcharge if I have to spend more than fifteen minutes with the parents.`,
`If they start to drive you nuts, tell them you know this great game called "cemetery." They have to lie on the floor and pretend they're dead. The first one to move or make a sound loses.`,
`And the vocabulary word for tonight is "indemnification."`,
`I know that plenty of guys want to go out with you, and plenty of girls want to go out with me, and that makes me think we should be together.`,
`Raisins are nature's candy.`,
`So Cinderella skipped the ball and asked her fairy Godmother to make her the first woman president. Realizing that the monarchy was becoming obsolete, the prince opened a video store.`,
`And then, the little engine decided that he just wasn't the competitive type.`,
`So Old Mother Hubbard tracked down the deadbeat loser and made him pay child support.`,
`And the dish ran away with the spoon, but Hawaii was the only state which would recognize the marriage as legal.`,
`And the truth is, no one will ever ask to see your permanent record.`,
`Gee, Mom and Dad never told us that people can think for themselves.`,
`We made up that part about aliens living under the North Pole.`,
`Tonight, on Sick, Sad World, a prime-time special about people just like you, only more pathetic.`,
`Daria, your paper was excellent, and the original research was thought-provoking, although it would probably be considered a felony in most states.`,
`I mean, when a woman is elected president, it won't be because she got breast implants.`,
`Fourteen people pretended not to see me, five crossed the street to get away, seven ran, three called the police, and I'm pretty sure this one guy fired a shot.`,
`From the first time man and woman gazed upon themselves in the ripples of a sun-dappled pool, human beings have been blessed, and burdened, by awareness of their own image. But what does this have to do with your thighs?`,
`Of course it's gonna be harder to breathe, hon. Those nostrils are itty-bitty compared to the ones you had. Try breathing through your mouth.`,
`Oh, honey, nothing wrong with that nose. It's a pretty little schnoz!`,
`We all know about the terrible atrocities caused by America's lust for veal, but here's something nice you can do for calves: calf implants!`,
`I hate to see a young lady give up on herself at such a early age.`,
`Maybe you can inject collagen into your lips in the shape of a smile.`,
`Humor may lift your spirits, Daria, but it takes a professional to lift your buttocks! Doctor's joke! Have a nice day girls. And remember, money can make anyone look beautiful.`,
`If I didn't have such low self-esteem, she might have gotten to me.`,
`Aren't you a little worried that there may be a hell?`,
`You know, maybe I should get boobs. I bet if I got some boobs on credit, I can get the rest of the money in no time.`,
`You've got the kind of looks that make other girls mentally ill.`,
`If I had any dignity, do you think I'd be out here letting you try and teach me how to be cool?`,
`Is there another tight pants sale going on at the mall?`,
`Well, everybody knows that late curfews should be go to people who can use them: attractive and popular people with lots of friends.`,
`Hey, does this mean we get to wander in the desert for forty years?`,
`You know how there are people who go to car races on the chance that they might see a crash?`,
`What do those Supreme Court judges wear under their robes? Declassified government polaroids, next on Sick, Sad World.`,
`Can't you just punish us? I'd like to pay my check to society and get on with my life.`,
`Bureaucracy is the price we pay for impartiality.`,
`You honor, let me make it clear at the outset that this is not a witch hunt.`,
`The sad part is that these are the people responsible for my genetic makeup.`,
`Now, off to the exercise yard before lockup.`,
`These tired bones may be locked behind prison walls, but when I play this rusty old harp, my soul flies free as a bird.`,
`I suspect you have some scam worked out for yourself, but since I can't prove anything, I'm asking you not to rat on me.`,
`Where's your rock & roll power now? Hippie!`,
`They did mental stuff to her. I can tell.`,
`Haven't you already made enough mockery of our judicial system?`,
`I just want to confer with my distinguished counterpart on the prosecution.`,
`You can't seriously expect me to plea bargain. We're talking about a repeat offender here.`,
`It's our policy to be tough, especially on youthful transgressors.`,
`But think of the effort you have to spend on incarceration. Scrabble... Risk... Monopoly... Operation.`,
`I got off. Enjoy prison.`,
`Kevin, I already told you, my parents did not conduct experiments on me.`,
`All right. I had a magnetic device implanted in my head.`,
`There's no sadder sight on this Earth than a football player trying to think.`,
`Can monkeys surf the net... and corrupt our kids? Chimpanzee chat rooms, next on Sick, Sad World.`,
`And I thought you were on your way to a sci-fi convention.`,
`No, thanks. Reality is bizarre enough for me.`,
`Sounds like one of those Doors cover bands that play brew pubs.`,
`It has a beat and you can dance to it, if you have no shame.`,
`We're borrowing our drummer's van, the Tank. It's indestructible.`,
`Friends don't let short-waisted friends wear hip-huggers.`,
`If I were gonna shoplift, I wouldn't take that cheap thing.`,
`You don't need any more holes in your head.`,
`Wow, you look almost normal. Is this some kind of trick?`,
`Don't panic. I think we'll be able to lose each other in a crowd of ten thousand.`,
`I'm doing ten to fifteen for armed robbery. What are you in for?`,
`Hey man, we're artists. Who knows where we'll be in five years.`,
`And this guy's not about selling out. ...'Cause for that to happen, you'd need someone interested in buying.`,
`Anybody else smell peanut butter?`,
`Looks like a sandwich... and it's an antique!`,
`Why didn't I just stay home, where it's nice and quiet and nothing ever happens?`,
`I hate to tell you this, but there's a big, greasy spot of peanut buttery goodness on your butt.`,
`I thought you looked depressed. You want a booster seat?`,
`Ever thought of becoming a waitress?`,
`Can you rig that glue gun of yours to shoot bullets? I'm ready to end my suffering.`,
`Well, you're not your usually sunny self.`,
`I've got a bump on my head, a bug bite on my arm, a sandwich on my ass...`,
`Now turn the knife counterclockwise. I can't go back out there. You go on to Alternapalooza; tomorrow, I'll emerge and begin my new life as a waitress.`,
`Now what are you gonna do about that stain on your butt?`,
`This is like that R.E.M. video, except you can't read anyone's mind.`,
`You can pee behind those trees. See those trees? You can pee behind there!`,
`If I'm not back in ten minutes, don't send help.`,
`Stop staring at me, you squirrel pervert!`,
`I'm going to the picnic, and I'm bringing asbestos insulation, brine shrimp, the cryogenically frozen head of Walt Disney... and a dromedary.`,
`I got a tattoo out of a magazine.`,
`Do you ever feel like maybe you're wasting your life? Only when I'm awake.`,
`No money, no job, you live with your parents, and you still can't play an open D tuning.`,
`Maybe I will end up a townie doing Doors covers. I mean, who's to say, right?`,
`It takes a lot of guts to go after a dream, especially when you know that failure can mean spending the rest of your life playing "L.A. Woman"... in public.`,
`I find the situation unbelievable myself.`,
`Are you my Mommy?`,
`I should really make pancakes more often. The batter's so sensual.`,
`Well, I got the bad news from the periodontist. Six months worth of gum work, eight hundred dollars a month.`,
`Oh, no! Get the camera.`,
`Guano see some gutsy climbing? Scaling the world's tallest pile of seagull droppings, next on Sick, Sad World.`,
`I hope the raging envy you're feeling won't affect our friendship.`,
`Then I'm afraid the fever has reached your brain, and you'll have to be destroyed.`,
`We're the black sheep of the clan. We're only invited because hating us brings them all closer together.`,
`You know, a weekend in the woods is starting to look pretty good.`,
`See that skeleton? That's our future.`,
`As soon as we get there, we find a bar, and we don't leave it until we're unconscious.`,
`She wears those straw hats. Thinks they're country or something. They look like the kind they put on horses to keep the sun off their heads.`,
`No phone, no fax, no e-mail, no voicemail! No way to contact the outside world! What a luxury.`,
`We don't need big business electricity! We don't need manufactured foods! We don't need chemically-softened toilet paper!`,
`So let's just walk in and meet them straight on. They're not going to intimidate us.`,
`I think she's a little disappointed in the Mexican job market. She may try Nicaragua next.`,
`He's thinking about getting remarried if he can just figure out whether his divorces were legal.`,
`Look at that, Daria: a fork in the trail. If you go one way, you can't go the other.`,
`It makes me yearn for the past.`,
`This is going to depress me, isn't it?`,
`This way over here leads to an entry-level job. A little bit of money in your pocket. Soon, you're wearing a suit and tie every day like all the other faceless saps, living in a boring little house in a bland little town, and doing so well you're in debt up to your disappearing hair!`,
`He can drive, he never has to take a pop quiz, and he can order a mimosa anytime he wants. What's the problem?`,
`You're so young, so beautiful. You should lead the tribe into the new century.`,
`Your Mom sounds a little nutty but she's making perfect sense.`,
`All right, let's not get panicked. We're going to look at the situation calmly and objectively. Agreed?`,
`We're out in the middle of nowhere, nobody knows we're here, we have no way to contact anyone, and our parents have gone insane.`,
`My family went crazy from eating psychotropic berries, so we were evacuated from the woods and they had their stomachs pumped.`,
`Now, you claim that not only did you see a yeti, but he was wearing a business suit and carrying an attaché case?`,
`I don't like to smile unless I have a reason.`,
`Yes, and I believe there is something intrinsically wrong with that system, and have dedicated myself to changing it.`,
`Too much hero worship isn't healthy, you know.`,
`It is my privilege today to once again send the message that learning is no substitute for winning.`,
`Congratulations, you must have worked very hard to become such a colossal jerk so quickly.`,
`Did someone flash the bimbo signal?`,
`You're one of those misery chicks, always moping about what a cruel world it is, making a big deal about it so people won't notice that you're a loser.`,
`What bothers me is that jerk is going to be treated like a hero for the rest of this life.`,
`It's weird. One minute he's standing there calling me a loser, the next minute he's dead.`,
`I mean, it really makes you think. Got any, like, words of wisdom or whatever?`,
`I figure you think about depressing stuff a lot. You're that type, you know?`,
`I feel bad, but I think I should feel worse, and not feeling worse makes me feel bad all over again.`,
`The dark side of life. The thoughts other people try not to have. That's your thing, right? Facing the void? Yes, I'm sure you're dealing with it. I'm not dealing with it!`,
`Quinn, what a wonderful impulse. To make something positive come out of this devastating event.`,
`I feel great. How else could I feel? I'm the misery chick.`,
`Tragedy hits the school and everyone thinks of me. A popular guy died, and now I'm popular because I'm the misery chick. But I'm not miserable. I'm just not like them.`,
`Yeah, well, I don't like it when I say people should die and then they do. I don't want that kind of responsibility. At least not until I've got a job in middle management.`,
`Well, he's acknowledging that if something makes you feel good, like being in love, there must be a corresponding painful side, like losing a love, and that it's just a fact of life.`,
`I'm afraid that inflation has forced me to institute a small fee for my services.`,
`Find some other way to feel. Then you won't feel sad.`,
`You just made ten bucks off of that poor girl's suffering.`
]