const seasonOne = [
`I'm just saying you don't make friends as easily as... uh, some people.`,
`I'll try to help her through this difficult period of adjustment.`,
`Don't worry. It's a psychological test. You're automatically exempt.`,
`Um... a herd of beautiful wild ponies running free across the plains.`,
`Last time I took one of these tests, they told me they were clouds. They said they could be whatever I wanted.`,
`Daria, can you concisely and unemotionally sum up for us the doctrine of Mainfest Destiny?`,
`A lot of good men died in that conflict, Kevin. I believe we owe it to them to at least get the century right!`,
`Well, my history teacher hates me because I know all the answers, but there are some interesting idiots in my class.`,
`Not much chance of that happening... unless there's uranium in the drinking water here, too`,
`We tell you over and over again that you're wonderful and you just... don't... get it! What's wrong with you?!`,
`Is she going to have, like, a breakdown or something? 'Cause that could really mess me up with my new friends.`,
`Don't worry. I don't have low self-esteem. It's a mistake. I have low esteem for everyone else.`,
`But we are here to begin realizing your actuality... and when we do, each and every one of you will be able to stand proudly and proclaim, "I am."`,
`He doesn't know what it means. He's got the speech memorized. Just enjoy the nice man's soothing voice.`,
`Nocturnal emissions.`,
`I could pass the test, but I like having low self-esteem. It makes me feel special.`,
`I'm taking the rest of the day off to work with you on your self-esteem.`,
`U.F.O. conventions, once sneered at as the domain of so-called "kooks," have become big, big business, drawing hundreds of thousands of people each year, people as sane and rational as you and I, who come simply to satisfy a normal curiosity.`,
`And once again, the bake sale was a tremendous success. We raised more than $400, which was subsequently stolen from the office, but I am confident we will get that money back. In a related note, the school nurse will be visiting homerooms tomorrow to collect DNA samples.`,
`Usually when I have this dream I'm wearing pink taffeta.`,
`You know, self-esteem is a little like your car's brake fluid. You may not even know you're low on it until, one day, you go to shift gears and nothing happens. ...That's transmission fluid!`,
`Knowing that I have self-esteem gives me even more self-esteem. On the other hand, having all of you know that I had low self-esteem makes me feel... kind of bad... like a big failure or something.`,
`I don't know. My self-esteem feels like it's starting to slip.`,
`Let's go get our picture taken with the cardboard alien.`,
`I'll wait here... or in the ladies' room.. or maybe out in the parking lot.`,
`Careful. Don't hurt yourself with that scrunchie.`,
`Perspective is hard.`,
`I'm thinking of going into politics.`,
`You can't expect me to choose a boyfriend right away. That would be like eating the first pancake off the stove. You have to feed one to the dog.`,
`Well, you could show me how to twirl hair around my little finger and look vacant.`,
`I know what you mean... and that scares me.`,
`Hey, even though I'm much more popular, we have some things in common.`,
`I mean, you're not popular, but you're not so unpopular that you couldn't come to my party Saturday night.`,
`Gee, Brittany. I'm overcome with emotion.`,
`Oh, yeah. That particular model was quite bursty. I think she had her bursts done.`,
`Sure. And after that, I think I'll swallow glass.`,
`It won't work. My face is too expressive.`,
`Sheer, semi-sheer, or opaque? ...Textured! `,
`Go away, I'm concentrating. I'm invited to a party Saturday night and I have to choose the perfect outfit.`,
`You know, I really should broaden my social horizons.`,
`Hey, stuff like that doesn't matter. The most popular people with the best-looking hair -- that's what makes a great party.`,
`Daria, would you say sleeping with a guitar in your hands counts as practicing? ...As long as you don't drop it.`,
`I have a problem dealing with authority.`,
`A high school party? Please. Don't you think I'm a little mature for that?`,
`Nice conversational skills.`,
`So I said, "Just because people are cliquey and snotty is no reason not to like them."`,
`Now she's really popular, but not as popular as she is. He's medium popular, and he just bought a great car so soon he'll be getting more popular. That guy was just popular enough to be invited, but now he needs to hook up with a girl who's more popular than he is.`,
`This is Jane. She wasn't invited, but she's good in art.`,
`I dissected her frog.`,
`Now, she used to be very popular, but then then there was that unfortunate nose job. That one behind the tiger? She was new and cute so she became, like, popular overnight. Those three aren't popular at all. I don't know what they're doing here. Maybe some kind of exchange program.`,
`The one in the green shirt is cute... in a head-too-big-for-his-body kind of way.`,
`Hey. Partying hard or hardly partying? ...Hardly interested.`,
`We were born in this room, we grew up in this room, and we thought we would die here... alone. But now you've arrived, and our lives can truly begin.`,
`Aren't you a little out of place here? And everywhere else on Earth?`,
`Well, I have been saving up for a pair of snappy orthopedic shoes.`,
`What do you plan to do about it? You can't ignore me! I pay your salary. Are you sleeping in there? You're not a real cop, you know!`,
` It's the Soul Train. Beep-beep. Get on board.`,
`You seem awfully young to be doing this kind of work.`,
`It's a disguise, ma'am. We're actually much older. Not as old as you, of course, ma'am.`,
`The wall-to-wall carpeting in the bathrooms makes up for it.`,
`To your left, the home of the town director of public works, built on unstable landfill. To your right, a flattened squirrel. Straight ahead, the future!`,
`I've been working on the railroad... come on, guys, we know this one.`,
`It was dead already, sweetheart. Just like the others.`,
`I think people who run over animals should get run over themselves to see how they like it.`,
`Can we get on with this? I have someplace to go. Television counts as a place.`,
`She's got a dark, threatened look. She never cracked no books. La-la-la...`,
`Superb! Now I can use your dorm room to carry on affairs with some of the more beautiful undergraduates. Thank you!`,
`How come even in my fantasies everyone's a jerk?`,
`Money well spent, since it wasn't my money.`,
`It's not a date. We're meeting to discuss scholarship options.`,
`There's no such thing as a making-out scholarship.`,
`These buildings date from when Middleton was a colonial religious college. Back then, the all-male student body attended chapel twice a day, and endured whippings as punishment for impure thoughts.`,
`Then you'd better get over there and help clean the house steps, or the Council of Ancients will give you a noodle whipping you won't soon forget.`,
`She's God's problem now, kid. Let's get out of here. This place gives me the creeps.`,
`Actually, I'm sending an erotic letter to a female inmate I met on the Internet. I think she's female.`,
`There's also the part about working a stupid job and begging your parents for money.`,
`My psych term paper. Finally. Nobody respects deadlines anymore. It was a collaboration. My part was to say how long it should be and when it was due.`,
`But cash only. I don't take checks from college students.`,
`Um, I'm just a freshman and I... we're not really supposed to... I get headaches sometimes 'cause I'm allergic to things. And I... I sort of have to go now, bye.`,
`It's a candy store. That's their business. They sell candy. And make loans. Oh, and haul trash. They got a variety of interests, actually.`,
`Second, unless your ex-boyfriend is an authority on D.H. Lawrence, don't base your thesis on something he said while making out.`,
`You seem pretty comfortable with the brain-dead. So, let's go to a party.`,
`Excuse me, ma'am. Could I trouble you for your underwear?`,
`But you look so cute when you say funny words. Besides, shouldn't you be saving your quarters for taking us out?x`,
`Ah, they've chosen the Keg Queen. It's a huge honor. She gets to drive the kegs to and from the distributor.`,
`They made me their queen! Isn't it great?!`,
`Uh, are we going to need to know this, or is this, like, personal advice or something?`,
`Thrown out of college without enrolling first. I'm damn proud of you.`,
`I have two econ problem sets and a paper on Kerouac that I have to get to the delivery guy by 9:00 P.M.... and then, I quit.`,
`I already feel burned out on college and I'm still in high school.`,
`She said it was wrong to encourage cheaters and to profit from them. ...So, she's giving up being a lawyer?`,
`Does that mean these are the best years of our lives? I hope not.`,
`I can't take anymore of this Shakespeare dude, bro. He's, like, a total chick writer!`,
`Like, why should I be interested in anything this Shakespeare guy says?`,
`Come together with the planet? By staring at a screen for hours? Sitting in a room full of people you never say a word to?`,
`Then I'd like to register as a conscientious objector.`,
`Hi! No dinner for me! Emergency meeting of the Fashion Club!`,
`I'll make up a nice plate for you and cover it up with cling wrap.`,
`I'll throw another steak on the grill.`,
`Can't talk now. I'm chairing a meeting of the Resting Quietly Club.`,
`Um, no... but I once had to recite the Gettysburg Address wearing a rainbow wig and panties that said "Tuesday." Whatever made me want to join a fraternity?`,
`Maybe that one about feeling like a big misfit whom everybody hates. The other kids will really relate to that. I know I do.`,
`No way, baby.`,
`Come on. Do it for friendship.`,
`I have no friends. I walk alone.`,
`Then do it for the opportunity to look inside people's houses and find out what screwed-up tastes they have.`,
`I'm bringing a Polaroid.`,
`You've come, no doubt, to apologize for your academic performance.`,
`It's good to see you both enterprising! I could make a trite observation about wishing you were as enterprising toward your school work as you are to this effort to find financing for a new place to loaf, but am I the sort of man who engages in trite observations, Brittany?`,
`Now, while you're on a roll, am I the sort of man who you suppose believes in underwriting the indolence of students who already display the work habits of garden slugs?`,
`Hi! I'm selling long distance phone cards.`,
`Well, I enjoy chocolate. Doctor says I'm not supposed to have too much of it, but he wouldn't mind if it's for a good cause.`,
`Just, just, I was in the basement when the doorbell rang. Need to catch my breath a little. How many chocolate bars you got there?`,
`You sure that's okay with your doctor?`,
`We could call your doctor or the hospital if you like. Otherwise, we'll be going.`,
`I don't need a damn doctor, I need a damn chocolate bar! Gimme! I'll pay ya five bucks apiece!`,
`Yeah, and all we had to do was take a human life.`,
`You always see the downside, don't you?`,
`Did she ask you to feed her the chocolate?`,
`She has no family. She ate them.`,
`So, your refusal to sell chocolate to this woman was based purely on concern for her welfare....And not wanting to do time for manslaughter.`,
`I'm here. But where are you? Sure, I see your body. Anybody home in that rotting bag of flesh? `,
`See? You don't want to do poetry for this crowd.`,
`You think it's too late for me to learn juggling?`,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
``,
]